export {
  initYsdk as initYandexGames,
  initYsdk,
  subscribeToFullscreenAds,
  ysdkGameplayStart,
  ysdkGameplayStop,
  ysdkGetLanguage,
  ysdkLoad,
  ysdkIsPlayerAuthorized,
  ysdkReady as notifyYandexGameReady,
  ysdkReady,
  ysdkRequestAuthorization,
  ysdkSave,
  ysdkSetLeaderboardScore,
  ysdkGetLeaderboardEntries,
  ysdkShowAd as showYandexFullscreenAd,
  ysdkShowAd,
  ysdkShowRewardedAd as showYandexRewardedAd,
  ysdkShowRewardedAd,
  type GameLanguage,
  type RewardedAdResult,
  type YsdkFullscreenAdCallbacks,
  type YsdkLeaderboardEntries,
  type YsdkLeaderboardEntry,
} from "@/sdk/yandex";
