export {
  initYsdk as initYandexGames,
  initYsdk,
  subscribeToFullscreenAds,
  ysdkGameplayStart,
  ysdkGameplayStop,
  ysdkGetLanguage,
  ysdkLoad,
  ysdkIsPlayerAuthorized,
  ysdkReady as notifyYandexGameReady,
  ysdkReady,
  ysdkRequestAuthorization,
  ysdkSave,
  ysdkShowAd as showYandexFullscreenAd,
  ysdkShowAd,
  ysdkShowRewardedAd as showYandexRewardedAd,
  ysdkShowRewardedAd,
  type GameLanguage,
  type RewardedAdResult,
  type YsdkFullscreenAdCallbacks,
} from "@/sdk/yandex";
