export {
  initYsdk as initYandexGames,
  initYsdk,
  isRewardedAdAvailable,
  subscribeToFullscreenAds,
  ysdkGameplayStart,
  ysdkGameplayStop,
  ysdkGetLanguage,
  ysdkLoad,
  ysdkIsPlayerAuthorized,
  ysdkReady as notifyYandexGameReady,
  ysdkReady,
  ysdkRequestAuthorization,
  ysdkSave,
  ysdkShowAd as showYandexFullscreenAd,
  ysdkShowAd,
  ysdkShowRewardedAd as showYandexRewardedAd,
  ysdkShowRewardedAd,
  type GameLanguage,
  type YsdkRewardedCallbacks,
  type YsdkFullscreenAdCallbacks,
} from "@/sdk/yandex";
